package telemetry

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"strings"
	"testing"
)

// makeSampleNodeInfo returns a NodeInfo with deterministic content used by
// both the byte-layout test and the golden vector test.
func makeSampleNodeInfo() NodeInfo {
	var genesis [32]byte
	for i := range genesis {
		genesis[i] = 0xA0 + byte(i)
	}
	var peer [32]byte
	for i := range peer {
		peer[i] = 0x10 + byte(i)
	}
	var ipv6 [16]byte
	for i := range ipv6 {
		ipv6[i] = byte(i)
	}
	return NodeInfo{
		JAMParameters: []byte{0xDE, 0xAD, 0xBE, 0xEF}, // placeholder until canonical encoder lands
		GenesisHash:   genesis,
		PeerID:        peer,
		PeerIPv6:      ipv6,
		PeerPort:      9000,
		NodeFlags:     NodeFlagPVMRecompiler,
		ImplName:      "JAMneration",
		ImplVersion:   "0.1.0",
		GrayPaperVer:  "0.7.2",
		FreeformInfo:  "hello",
	}
}

// ---------------------------------------------------------------------------
// Field layout: protocol version is FIRST, no Timestamp / Discriminator.
// This is the regression for the JIP-3 design finding: putting Timestamp
// at the head of NodeInfo shifts every subsequent field by 8 bytes and
// JamTART rejects the connection.
// ---------------------------------------------------------------------------

func TestNodeInfo_ProtocolVersionFirstByte(t *testing.T) {
	n := makeSampleNodeInfo()
	enc, err := n.Encode()
	if err != nil {
		t.Fatal(err)
	}
	if len(enc) == 0 {
		t.Fatal("empty encoding")
	}
	if enc[0] != NodeInfoProtocolVersion {
		t.Fatalf("first byte = 0x%02x, want protocol version 0x%02x",
			enc[0], NodeInfoProtocolVersion)
	}
}

// ---------------------------------------------------------------------------
// Field layout: verify each segment lands at the expected offset for a
// known input. This catches accidental field reordering on later edits.
// ---------------------------------------------------------------------------

func TestNodeInfo_FieldLayout(t *testing.T) {
	n := makeSampleNodeInfo()
	enc, err := n.Encode()
	if err != nil {
		t.Fatal(err)
	}

	pos := 0

	// 1. protocol version (u8)
	if enc[pos] != NodeInfoProtocolVersion {
		t.Fatalf("protocol version at %d: got 0x%02x", pos, enc[pos])
	}
	pos += 1

	// 2. JAM Parameters (raw opaque bytes)
	if !bytes.Equal(enc[pos:pos+len(n.JAMParameters)], n.JAMParameters) {
		t.Fatalf("JAMParameters at %d mismatch", pos)
	}
	pos += len(n.JAMParameters)

	// 3. Genesis hash (32 bytes)
	if !bytes.Equal(enc[pos:pos+32], n.GenesisHash[:]) {
		t.Fatalf("GenesisHash at %d mismatch", pos)
	}
	pos += 32

	// 4. Peer ID (32 bytes)
	if !bytes.Equal(enc[pos:pos+32], n.PeerID[:]) {
		t.Fatalf("PeerID at %d mismatch", pos)
	}
	pos += 32

	// 5a. Peer IPv6 (16 bytes)
	if !bytes.Equal(enc[pos:pos+16], n.PeerIPv6[:]) {
		t.Fatalf("PeerIPv6 at %d mismatch", pos)
	}
	pos += 16

	// 5b. Peer port (u16 LE)
	gotPort := uint16(enc[pos]) | uint16(enc[pos+1])<<8
	if gotPort != n.PeerPort {
		t.Fatalf("PeerPort at %d: got %d want %d", pos, gotPort, n.PeerPort)
	}
	pos += 2

	// 6. Node flags (u32 LE)
	gotFlags := uint32(enc[pos]) | uint32(enc[pos+1])<<8 |
		uint32(enc[pos+2])<<16 | uint32(enc[pos+3])<<24
	if gotFlags != n.NodeFlags {
		t.Fatalf("NodeFlags at %d: got 0x%x want 0x%x", pos, gotFlags, n.NodeFlags)
	}
	pos += 4

	// 7-10. Strings: each is len++[u8]. Decode them back via Decoder
	// rather than recompute lengths by hand.
	d := NewDecoder(enc[pos:])

	implName, err := d.ReadString(maxImplName)
	if err != nil || implName != n.ImplName {
		t.Fatalf("ImplName: %q err=%v", implName, err)
	}
	implVer, err := d.ReadString(maxImplVersion)
	if err != nil || implVer != n.ImplVersion {
		t.Fatalf("ImplVersion: %q err=%v", implVer, err)
	}
	gpVer, err := d.ReadString(maxGrayPaperVer)
	if err != nil || gpVer != n.GrayPaperVer {
		t.Fatalf("GrayPaperVer: %q err=%v", gpVer, err)
	}
	freeform, err := d.ReadString(maxFreeformInfo)
	if err != nil || freeform != n.FreeformInfo {
		t.Fatalf("FreeformInfo: %q err=%v", freeform, err)
	}

	if !d.Done() {
		t.Fatalf("trailing bytes: %d remaining", d.Remaining())
	}
}

// ---------------------------------------------------------------------------
// Golden vector: snapshot bytes for a fixed input.
//
// This is a self-consistent vector (we generated it from the encoder we
// committed) rather than against an external reference. Once the
// canonical JAM Parameters encoding source is confirmed and JamTART /
// JIP-3 / GP reference fixtures are obtained, we can replace the
// expectedHex below with the externally-verified value.
//
// TODO(jip3-golden-source): replace with externally-verified vector.
// ---------------------------------------------------------------------------

func TestNodeInfo_GoldenVector(t *testing.T) {
	enc, err := makeSampleNodeInfo().Encode()
	if err != nil {
		t.Fatal(err)
	}

	// Generated by makeSampleNodeInfo + Encode at the time of this commit.
	// Layout (offsets in bytes):
	//   [0]     protocol version = 0x00
	//   [1:5]   JAM Parameters = DEADBEEF
	//   [5:37]  GenesisHash    = A0..BF
	//   [37:69] PeerID         = 10..2F
	//   [69:85] IPv6           = 00..0F
	//   [85:87] Port           = 9000 LE = 28 23
	//   [87:91] NodeFlags      = 1 LE = 01 00 00 00
	//   [91:..] Strings (len-prefixed)
	expectedHex := "" +
		"00" +
		"deadbeef" +
		"a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf" +
		"101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f" +
		"000102030405060708090a0b0c0d0e0f" +
		"2823" +
		"01000000" +
		"0b" + hex.EncodeToString([]byte("JAMneration")) + // String<32> "JAMneration" (len 11)
		"05" + hex.EncodeToString([]byte("0.1.0")) + // String<32> "0.1.0"        (len 5)
		"05" + hex.EncodeToString([]byte("0.7.2")) + // String<16> "0.7.2"        (len 5)
		"05" + hex.EncodeToString([]byte("hello")) //  String<512> "hello"       (len 5)

	expected, err := hex.DecodeString(expectedHex)
	if err != nil {
		t.Fatalf("expectedHex parse: %v", err)
	}
	if !bytes.Equal(enc, expected) {
		t.Fatalf("golden vector mismatch\n  got:  %x\n  want: %x",
			enc, expected)
	}
}

// ---------------------------------------------------------------------------
// String<N> length cap rejection per field
// ---------------------------------------------------------------------------

func TestNodeInfo_LengthCaps(t *testing.T) {
	tests := []struct {
		name   string
		mutate func(*NodeInfo)
	}{
		{"ImplName too long", func(n *NodeInfo) { n.ImplName = strings.Repeat("x", int(maxImplName)+1) }},
		{"ImplVersion too long", func(n *NodeInfo) { n.ImplVersion = strings.Repeat("x", int(maxImplVersion)+1) }},
		{"GrayPaperVer too long", func(n *NodeInfo) { n.GrayPaperVer = strings.Repeat("x", int(maxGrayPaperVer)+1) }},
		{"FreeformInfo too long", func(n *NodeInfo) { n.FreeformInfo = strings.Repeat("x", int(maxFreeformInfo)+1) }},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			n := makeSampleNodeInfo()
			tc.mutate(&n)
			if _, err := n.Encode(); err == nil {
				t.Fatalf("expected length-cap error")
			}
		})
	}
}

// ---------------------------------------------------------------------------
// UTF-8 rejection: any String field with invalid UTF-8 fails Encode.
// ---------------------------------------------------------------------------

func TestNodeInfo_RejectsInvalidUTF8(t *testing.T) {
	bad := string([]byte{0xFF, 0xFE, 0xFD})
	n := makeSampleNodeInfo()
	n.ImplName = bad
	if _, err := n.Encode(); err == nil {
		t.Fatal("expected UTF-8 error for ImplName")
	}
}

// ---------------------------------------------------------------------------
// Empty FreeformInfo is allowed (encodes as len-zero).
// ---------------------------------------------------------------------------

func TestNodeInfo_EmptyFreeformInfo(t *testing.T) {
	n := makeSampleNodeInfo()
	n.FreeformInfo = ""
	enc, err := n.Encode()
	if err != nil {
		t.Fatal(err)
	}
	// Last byte should be 0x00 = len-zero natural prefix for empty string
	if enc[len(enc)-1] != 0 {
		t.Fatalf("expected empty FreeformInfo to end with 0x00, got 0x%02x", enc[len(enc)-1])
	}
}

// ---------------------------------------------------------------------------
// PVM flag bit semantics
// ---------------------------------------------------------------------------

func TestNodeInfo_PVMFlag(t *testing.T) {
	n := makeSampleNodeInfo()
	n.NodeFlags = 0
	enc, err := n.Encode()
	if err != nil {
		t.Fatal(err)
	}
	// NodeFlags is at offset 87 in the sample (see layout test). Read u32 LE.
	flags := uint32(enc[87]) | uint32(enc[88])<<8 | uint32(enc[89])<<16 | uint32(enc[90])<<24
	if flags != 0 {
		t.Fatalf("interpreter mode flags should be 0, got 0x%x", flags)
	}

	n.NodeFlags = NodeFlagPVMRecompiler
	enc, err = n.Encode()
	if err != nil {
		t.Fatal(err)
	}
	flags = uint32(enc[87]) | uint32(enc[88])<<8 | uint32(enc[89])<<16 | uint32(enc[90])<<24
	if flags&NodeFlagPVMRecompiler == 0 {
		t.Fatalf("recompiler bit should be set, got 0x%x", flags)
	}
}

// ---------------------------------------------------------------------------
// NodeFlags undefined-bits validation: JIP-3 only defines bit 0
// (PVMRecompiler). Encoding any other bit must fail at the encoder so a
// local mistake does not get pushed onto the aggregator's parser.
// ---------------------------------------------------------------------------

func TestNodeInfo_Encode_RejectsUndefinedNodeFlagsBits(t *testing.T) {
	cases := []struct {
		name  string
		flags uint32
	}{
		{"bit1", 1 << 1},
		{"bit31", 1 << 31},
		{"all-undefined", ^NodeFlagPVMRecompiler},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			n := makeSampleNodeInfo()
			n.NodeFlags = tc.flags
			_, err := n.Encode()
			if err == nil {
				t.Fatalf("Encode succeeded with NodeFlags=0x%08x; expected error", tc.flags)
			}
			if !strings.Contains(err.Error(), "NodeFlags") {
				t.Errorf("error %q does not mention NodeFlags", err.Error())
			}
		})
	}
}

func TestNodeInfo_Encode_AcceptsDefinedNodeFlags(t *testing.T) {
	for _, flags := range []uint32{0, NodeFlagPVMRecompiler} {
		t.Run(fmt.Sprintf("flags=0x%08x", flags), func(t *testing.T) {
			n := makeSampleNodeInfo()
			n.NodeFlags = flags
			if _, err := n.Encode(); err != nil {
				t.Errorf("Encode rejected valid NodeFlags=0x%08x: %v", flags, err)
			}
		})
	}
}
